Clarify the possibility of passing in an -E expression
icetan/mavenix pull request #17
Opened 2019-04-02 14:05 UTC by FRidh

2019-04-02 14:42 UTC, icetan requested changes
Very nice!

I had forgotten about this feature :)

2019-04-02 14:42 UTC, icetan commented on README.md
> +mvnix-update -E "import ./. {}; pkgset.pkg"
For correctness I would suggest.

```suggestion
mvnix-update -E "with import ./. {}; pkgset.pkg"
```

or

```suggestion
mvnix-update -E "(import ./. {}).pkgset.pkg"
```

2019-04-03 07:26 UTC, FRidh commented
Right, done.

I'm building a package set and would like each package to have a Nix expression its own repo, overriding the attribute in the main package set using an overlay. Using this feature that's possible :)

2019-04-03 08:06 UTC, icetan approved these changes

2019-04-03 08:06 UTC, merged